// Mock data for prototype demonstration

export const mockProperties = [
  {
    id: "1",
    name: "Sushant Lok",
    slug: "sushant-lok",
    address: "Sector 57, Phase 2, Sushant Lok, Gurugram, Haryana",
    pincode: "122011",
    coordinates: "28.4212° N, 77.0761° E",
    description: "Your peaceful retreat in the heart of Gurugram",
    vibe: "Peaceful surroundings, great connectivity — perfect for work or to unwind. This home combines the calm of a residential neighborhood with easy access to Gurugram's business districts and dining scene.",
    baseRate: 4500,
    weekendRate: 5500,
    cleaningFee: 500,
    maxGuests: 6,
    checkInTime: "14:00",
    checkOutTime: "11:00",
    amenities: [
      "High-Speed Wi-Fi",
      "Smart TV with streaming",
      "Fully equipped kitchen",
      "Air conditioning",
      "Spacious living area",
      "Dedicated workspace",
      "24/7 hot water",
      "Free parking",
      "Garden access",
      "Security system"
    ],
    policies: "No smoking indoors. Pets negotiable. Quiet hours 10 PM - 8 AM. Events require prior approval.",
    isActive: true,
  },
  {
    id: "2",
    name: "Jharsa Village",
    slug: "jharsa-village",
    address: "593, Durga Colony, Jharsa Village, Sector 39, Gurugram, Haryana - 122003",
    pincode: "122003",
    coordinates: "28.4594° N, 77.0266° E",
    description: "Your cozy neighborhood escape",
    vibe: "Cozy neighborhood, close to everything — your happy place in the city. Experience authentic local life while staying minutes away from Cyber Hub, malls, and metro connectivity.",
    baseRate: 4000,
    weekendRate: 5000,
    cleaningFee: 500,
    maxGuests: 4,
    checkInTime: "14:00",
    checkOutTime: "11:00",
    amenities: [
      "High-Speed Wi-Fi",
      "Smart TV with Netflix",
      "Modern kitchen",
      "Air conditioning",
      "Cozy living space",
      "Work-friendly setup",
      "24/7 hot water",
      "Street parking",
      "Local market nearby",
      "Safe neighborhood"
    ],
    policies: "No smoking indoors. Pets negotiable. Quiet hours 10 PM - 8 AM. Please respect the neighborhood.",
    isActive: true,
  },
];

export const mockBookings = [
  {
    id: "BK001",
    bookingNumber: "MM2024001",
    propertyId: "1",
    propertyName: "Sushant Lok",
    guestName: "Arjun Mehta",
    guestEmail: "arjun.mehta@example.com",
    guestPhone: "9876543210",
    checkIn: new Date("2024-07-15"),
    checkOut: new Date("2024-07-18"),
    guestsCount: 4,
    totalAmount: 14500,
    status: "CONFIRMED",
    paymentStatus: "PAID",
    source: "DIRECT",
    notes: "Late check-in requested - approved",
    createdAt: new Date("2024-07-01"),
  },
  {
    id: "BK002",
    bookingNumber: "MM2024002",
    propertyId: "2",
    propertyName: "Jharsa Village",
    guestName: "Priya Sharma",
    guestEmail: "priya.sharma@example.com",
    guestPhone: "9876543211",
    checkIn: new Date("2024-07-20"),
    checkOut: new Date("2024-07-22"),
    guestsCount: 2,
    totalAmount: 10500,
    status: "CONFIRMED",
    paymentStatus: "PAID",
    source: "AIRBNB",
    createdAt: new Date("2024-07-05"),
  },
  {
    id: "BK003",
    bookingNumber: "MM2024003",
    propertyId: "1",
    propertyName: "Sushant Lok",
    guestName: "Rahul Verma",
    guestEmail: "rahul.v@example.com",
    guestPhone: "9876543212",
    checkIn: new Date("2024-07-25"),
    checkOut: new Date("2024-07-30"),
    guestsCount: 3,
    totalAmount: 23000,
    status: "PENDING",
    paymentStatus: "PENDING",
    source: "DIRECT",
    notes: "Requested extra pillows",
    createdAt: new Date("2024-07-06"),
  },
];

export const mockGuests = [
  {
    id: "G001",
    name: "Arjun Mehta",
    email: "arjun.mehta@example.com",
    phone: "9876543210",
    totalStays: 3,
    totalSpent: 42000,
    lastStay: new Date("2024-07-18"),
    notes: "Regular guest, prefers ground floor",
  },
  {
    id: "G002",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    phone: "9876543211",
    totalStays: 1,
    totalSpent: 10500,
    lastStay: new Date("2024-07-22"),
    notes: "First time guest, vegetarian",
  },
];

export const mockInquiries = [
  {
    id: "INQ001",
    name: "Anjali Kapoor",
    email: "anjali.k@example.com",
    phone: "9876543213",
    propertyId: "1",
    propertyName: "Sushant Lok",
    dates: "Aug 10-12, 2024",
    message: "Hi! Looking for a peaceful weekend getaway for 2 couples. Do you allow small gatherings?",
    status: "NEW",
    createdAt: new Date("2024-07-06"),
  },
  {
    id: "INQ002",
    name: "Vikram Singh",
    email: "vikram.singh@example.com",
    phone: "9876543214",
    propertyId: "2",
    propertyName: "Jharsa Village",
    dates: "July 28-30, 2024",
    message: "Need accommodation for a small team offsite. Can we get early check-in?",
    status: "REPLIED",
    reply: "Hi Vikram! Yes, we can accommodate your team. Early check-in is available for a small fee. Let me share the details...",
    createdAt: new Date("2024-07-05"),
  },
];

export const mockTeam = [
  {
    id: "T001",
    name: "Simran",
    role: "OWNER",
    title: "Your Host",
    phone: "8828352311",
    email: "simran@mehmaanmanor.com",
    avatar: null,
  },
  {
    id: "T002",
    name: "Vipin",
    role: "MANAGER",
    title: "Property Manager",
    phone: "8796568003",
    email: "vipin@mehmaanmanor.com",
    avatar: null,
  },
  {
    id: "T003",
    name: "Jyoti",
    role: "STAFF",
    title: "Guest Relations",
    phone: "8796568002",
    email: "jyoti@mehmaanmanor.com",
    avatar: null,
  },
];

export const mockRevenueData = [
  { month: "Jan", revenue: 45000 },
  { month: "Feb", revenue: 52000 },
  { month: "Mar", revenue: 61000 },
  { month: "Apr", revenue: 58000 },
  { month: "May", revenue: 67000 },
  { month: "Jun", revenue: 72000 },
];
